const API="http://127.0.0.1:8000/api/v1", projectId="demo";
let conversationId, settings={web_search_enabled:false,creativity_level:"balanced",retrieval_top_k:6,included_document_types:["text","table","image"]};
const $=selector=>document.querySelector(selector), toast=message=>{const node=$("#toast");node.textContent=message;node.classList.remove("hidden");setTimeout(()=>node.classList.add("hidden"),4500)};
async function api(path,options={}){const response=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...options.headers}});if(!response.ok)throw new Error(await response.text());return response.json()}
async function loadDocuments(){try{const documents=await api(`/projects/${projectId}/documents`);$("#document-list").innerHTML=documents.map(document=>`<button class="document" data-id="${document.id}">▤ <span><strong>${document.filename}</strong><small>${document.file_type.toUpperCase()} · ${document.status.replace("_"," ")}</small></span></button>`).join("");document.querySelectorAll(".document").forEach(button=>button.onclick=()=>openDocument(button.dataset.id));}catch(error){toast(error.message)}}
async function openDocument(id){try{const [document,elements]=await Promise.all([api(`/projects/${projectId}/documents/${id}`),api(`/projects/${projectId}/documents/${id}/elements`)]);$("#inspection").classList.remove("hidden");$("#inspection").innerHTML=`<p>INSPECTION</p><h2>${document.filename}</h2>${document.has_low_confidence_content?'<div class="notice">Partial extraction: review marked elements before relying on them.</div>':""}${document.failure_category?`<div class="notice">${document.failure_category.replaceAll("_"," ")}</div>`:""}${elements.map(element=>`<div class="element"><span class="badge ${element.confidence}">${element.confidence}</span>${element.element_type} · page ${element.page_number??"-"}${element.confidence_reason?`<br><small>${element.confidence_reason}</small>`:""}</div>`).join("")}`;}catch(error){toast(error.message)}}
async function startChat(){try{const conversation=await api(`/projects/${projectId}/conversations`,{method:"POST",body:"{}"});conversationId=conversation.id;settings=await api(`/projects/${projectId}/conversations/${conversationId}/settings`);syncSettings();$("#empty").classList.add("hidden");$("#conversation").classList.remove("hidden");$("#question").focus()}catch(error){toast(error.message)}}
function addMessage(role,content){const item=document.createElement("article");item.className=`message ${role}`;item.innerHTML=`<label>${role==="user"?"You":"AllSlate"}</label><p>${content}</p>`;$("#messages").append(item);item.scrollIntoView({behavior:"smooth",block:"end"});return item}
async function askQuestion(event){event.preventDefault();const input=$("#question"),question=input.value.trim();if(!question||!conversationId)return;input.value="";addMessage("user",question);const phase=document.createElement("div");phase.className="phase";phase.textContent="Retrieving sources...";$("#messages").append(phase);try{const response=await fetch(`${API}/projects/${projectId}/conversations/${conversationId}/ask`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});if(!response.ok)throw new Error(await response.text());const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const frames=buffer.split("\n\n");buffer=frames.pop()||"";frames.forEach(frame=>{const type=frame.match(/^event: (.+)$/m)?.[1],raw=frame.match(/^data: (.+)$/m)?.[1];if(!raw)return;const data=JSON.parse(raw);if(type==="phase")phase.textContent=data.phase==="generating"?"Writing answer...":"Retrieving sources...";if(type==="complete"){phase.remove();addMessage("assistant",data.content)}if(type==="failed")throw new Error(data.failure_reason)})}}catch(error){phase.remove();toast(error.message)}}
async function saveSettings(patch){if(!conversationId)return;try{settings=await api(`/projects/${projectId}/conversations/${conversationId}/settings`,{method:"PATCH",body:JSON.stringify(patch)});syncSettings()}catch(error){toast(error.message)}}
function syncSettings(){$("#web-search").checked=settings.web_search_enabled;$("#top-k").value=settings.retrieval_top_k;$("#top-k-value").textContent=settings.retrieval_top_k;document.querySelectorAll("#creativity button").forEach(button=>button.classList.toggle("active",button.dataset.level===settings.creativity_level));document.querySelectorAll('fieldset input[type="checkbox"]').forEach(input=>input.checked=settings.included_document_types.includes(input.value))}
$("#start-chat").onclick=startChat;$("#new-chat").onclick=startChat;$("#composer").onsubmit=askQuestion;$("#upload").onchange=async event=>{const file=event.target.files[0];if(!file)return;try{const body=new FormData();body.append("file",file);const response=await fetch(`${API}/projects/${projectId}/documents`,{method:"POST",body});if(!response.ok)throw new Error(await response.text());loadDocuments()}catch(error){toast(error.message)}event.target.value=""};$("#web-search").onchange=event=>saveSettings({web_search_enabled:event.target.checked});$("#top-k").onchange=event=>saveSettings({retrieval_top_k:Number(event.target.value)});document.querySelectorAll("#creativity button").forEach(button=>button.onclick=()=>saveSettings({creativity_level:button.dataset.level}));document.querySelectorAll('fieldset input[type="checkbox"]').forEach(input=>input.onchange=()=>{const types=[...document.querySelectorAll('fieldset input[type="checkbox"]:checked')].map(node=>node.value);if(types.length)saveSettings({included_document_types:types});else{input.checked=true;toast("Choose at least one document type.")}});$("#settings-toggle").onclick=()=>$(".settings").classList.toggle("closed");loadDocuments();